### ISSUE TITLE
Invitation app

### ISSUE THREAD

**Issue by Kamalnrf** [fcc-hyd/hackermonth#10]
Basically the idea is to build something like meetup.com but my idea is to do it as closed social media of only your friends and relatives...So basically you will invite people by there email id if that person is signed up he will get it as a invition in the app  then he will rsvp for the event... end of the day host will know how many people are attending so that they can plan accordingly....

I want to develop an android app,
for backend i want to use clojure...

<h3> Important links </h3> 

<a href="https://github.com/Kamalnrf/Invitation-app">github</a>
<a href="https://trello.com/invite/b/FQ8Vedyw/63c90d9bf88a60c5d402f3afadb6ab45/invitation-app">trello</a>
<a href="https://gitter.im/invitationapp/Lobby#">gitter</a>

<h3> Team </h3>
@sudheerdarla

**Comment by duttakapil** [comment]
Hey @Kamalnrf, good idea. Have you created the GitHub repo, the Trello board and the Gitter chatroom for this project? If so, can you update the description with those links? It will be easier to keep track of everything
