### ISSUE TITLE
Idea: Productivity Challenge Timer

### ISSUE THREAD

**Issue by boro741** [fcc-hyd/hackermonth#12]
## Features: 

1. Use Pomodoro technique.
2. Track progress by displaying graphs.
3.  Achievements list.
4. Notify schedule.
5. If we skip the schedule, rescheduling automatically.
     Ex:
           If I skip todays working hour like for 30 min. It should automatically reschedule and distribute evenly like tomorrow 30+15 min and day after tomorrow 30+15.

Similar app on playstore : [Productivity Challenge Timer](https://play.google.com/store/apps/details?id=com.wlxd.pomochallenge&hl=en)
[FCC-Pomodoro Clock](https://www.youtube.com/watch?v=lgj3nfzV0xM)

## Important Links:

[GitHub Repo](https://github.com/boro741/FCC-Productivity-Challenge-Timer)
[Gitter ChatRoom](https://gitter.im/FCC-Productivity-Challenge-Timer/Lobby)
[Trello Board](https://trello.com/b/PswXflFl/fcc-productivity-challenge-timer)

Team: 
@boro741 @nani554 @sahil78623 @pbteja1998

**Comment by nani554** [comment]
can i join

**Comment by duttakapil** [comment]
@boro741 this would be really cool to build. Can you update your description with the links to the GitHub repo, the Trello board and link to the Gitter chatrom you created for your team? It would be easier to keep track of this project and be in touch with all the members

**Comment by srtarun** [comment]
can i hook in

**Comment by boro741** [comment]
Sure @srtarun.
Join us at [gitter chatroom](https://gitter.im/FCC-Productivity-Challenge-Timer/Lobby).
