### ISSUE TITLE
Platform to share FCCcurriculum progress.

### ISSUE THREAD

**Issue by PrashanthVasa** [fcc-hyd/hackermonth#14]
The problem we are facing is that we want to pair up with someone and code but don't know with whom to pair up with.It is very difficult to ask  everyone . I think this can be solved by sharing their progress on a common platform and have an option to view people who are ready to pair up.

**Comment by duttakapil** [comment]
@PrashanthVasa I really love this idea. We could even make this part of our Community projects and use it in our future meetups, to help people pair. You should ask in our WhatsApp or Facebook group, if anyone would like to join your team and contribute. If that doesn't happen, let me know, we'll figure something out :)

**Comment by sudheerdarla** [comment]
Hey @PrashanthVasa update description with Trello board, gitter chatroom and your team members.

**Comment by duttakapil** [comment]
@sudheerdarla he hasn't formed his team yet. He is looking for them. 
@PrashanthVasa why don't you share your project idea in our chatrom and Facebook group?

**Comment by anushreddy** [comment]
I am interested but i have to work remotely if thats okay

**Comment by PrashanthVasa** [comment]
@anushreddy Working remotely is fine. I'm glad to have you as team member.

**Comment by anushreddy** [comment]
Is there a group ? To discuss the project

**Comment by duttakapil** [comment]
@PrashanthVasa has yet to create a Gitter room, GitHub repo and a Trello board. When you do that, let me know, I'll add the respective labels
