### ISSUE TITLE
Diary writing

### ISSUE THREAD

**Issue by gopikrishnagurram** [fcc-hyd/hackermonth#16]
dairy writing application, Storing important dates, Future remainders, Storing daily schedules like 6am to 8am, 10 am to 11 am, storing things want to do in life, giving options like saving very bad days, saving very happy days and their reasons, option to save enemy names, best friends names and inspirational people, key points learned in a day.

Important Links :

[Trello](https://trello.com/b/1VmLBdck)

[Gitter](https://gitter.im/mirror-dairy/Lobby)

[GitHub](https://github.com/gopikrishnagurram/Mirror/tree/master)

Team members : 
@kolaarunkumar @nikhil1 @naveenkumar2525 @hari457627

**Comment by duttakapil** [comment]
Interesting idea @gopikrishnagurram, are you looking for teammates for this project or have you already formed your team?

**Comment by udhayprakash** [comment]
Good idea. It is interesting.

**Comment by gopikrishnagurram** [comment]
Hi @duttakapil , We have team of five members, We are working on it.

**Comment by gopikrishnagurram** [comment]
thank you @udhayprakash

**Comment by duttakapil** [comment]
@gopikrishnagurram can you update the description with the links to your GitHub repo, Trello board and your Gitter chatroom? It would also help if you can tag all your teammates. Follow the example of issue https://github.com/fcc-hyd/hackermonth/issues/18. This will help us to keep track of the progress each team makes
