### ISSUE TITLE
My Extended Family

### ISSUE THREAD

**Issue by irfan-m-mohammad** [fcc-hyd/hackermonth#17]
## Description
People are related to one another in a way they can't even imagine. If the relationship between people is represented pictorially, one feels overwhelmed seeing the way someone is related to him/her. The application should help the user to know who he/she is related to! This application should be able to reconnect the families that have been dormant for years. 

## Features
The idea of the project is to develop an application with the following features  
- A relationship chart that shows the connections between people showing how they are related.
- A map interface that shows the location of their dear ones so that they can see who's nearby and plan a hangout. 
- A Newsfeed sort of tool for posting updates of events like marriages, parties etc. 

## Important Links
- [Github repository](https://github.com/nafri-irfan96/My-Extended-Family)
- [Trello Board](https://trello.com/b/duQBOmFx/my-extended-family)
- [Gitter Chatroom](https://gitter.im/My-Extended-Family)

## Team
@nafri-irfan96
@anshuedu
@AshishVishwakarma
@M-ZubairAhmed
@a-kile 
@srtarun 
@charan1922

**Comment by duttakapil** [comment]
Interesting idea @nafri-irfan96. Are you looking for team mates or have you already formed your team?

**Comment by irfan-m-mohammad** [comment]
@duttakapil I'm looking for teammates.

**Comment by duttakapil** [comment]
@nafri-irfan96 are you from Hyderabad or outside? You can make a post in our [Facebook group](http://fb.com/groups/free.code.camp.hyderabad), or ask in our [Gitter](https://gitter.im/fcc-hyd/general)/[WhatsApp](https://chat.whatsapp.com/6y8IeTuDTzpINbEX9jPHG9) chatroom. 

Give a brief description of your project and mention that you're looking for teammates to contribute. 

Once you have the team formed, update the description of this issue with the relevant info, Go through our  [Idea Session Summary document](https://goo.gl/CvlcMY) for more information.

**Comment by elevenpassin** [comment]
HOOOOOOOOOK ME IN!

**Comment by irfan-m-mohammad** [comment]
@a-kile Added you as a collaborator to the project. Join us on the [gitter chat](https://gitter.im/My-Extended-Family/).

**Comment by srtarun** [comment]
Interesting! can you hook me in?

**Comment by srtarun** [comment]
can i join the team.?

**Comment by irfan-m-mohammad** [comment]
@srtarun sure. Join us on the [gitter ](https://gitter.im/My-Extended-Family/)chat.

**Comment by M-ZubairAhmed** [comment]
@nafri-irfan96 please update the readme file here too.
