### ISSUE TITLE
Real-time Bus Tracking System

### ISSUE THREAD

**Issue by gangaaloori** [fcc-hyd/hackermonth#18]
Currently we do not have an application which provides real-time information about the public transport busses. People have no clue about the whereabouts of the bus they need to board to reach to their destination. So the idea (for now) is to build a simple web application to live-track a bus on google maps.

Important Links : 
[GitHub](https://github.com/gangaaloori/bus-tracker)
[Gitter](https://gitter.im/bus-tracker/Lobby)
[Trello](https://trello.com/b/oobHO2Ol/bus-tracker)

Team : 
@dheerajnani, @Sairammartha, @SravanChirra, @VinayKumarKola and @gangaaloori

**Comment by Raghuram42** [comment]
Hey guyss, 
I found these idea to be interesting and I wish to join with you guys.
What you say?

**Comment by sudheerdarla** [comment]
@gangaaloori you better reply because @Raghuram42 is waiting for your response... if it is not possible he will try to join in other ideas asap.

**Comment by duttakapil** [comment]
@Raghuram42 since this team already has 5 people, I would suggest you to either pick another one or contribute to this project when they create GitHub issues
