### ISSUE TITLE
Code Assistant  (A self  learner)

### ISSUE THREAD

**Issue by Raghuram42** [fcc-hyd/hackermonth#19]
As we have siri ,google now and dragon assist that we use for with voice commands right!
My idea is that to build a voice assit through Machine Learning that could build any type of project which may be a complex or simple project which would complete that project with our voice commands.
Here were don't even require to learn the new technology even non-technical person can even build projects with that voice assist.

That's my idea guys now say comment down want you think?

**Comment by duttakapil** [comment]
@Raghuram42 do you want to participate in Hacker Month with this idea? And are you looking for teammates for this? 
Also, you will need to make the title more descriptive. "self-learner" doesn't really explain anything about your idea.

**Comment by Raghuram42** [comment]
Yeah I'm looking for teammates!! @duttakapil

**Comment by duttakapil** [comment]
@Raghuram42 you can share this issue/idea in the WhatsApp, Gitter and Facebook group. You're far more likely to find teammates that way.

**Comment by sumant041** [comment]
Can u give an elaborative description of the Project ?

**Comment by Raghuram42** [comment]
Description it start forward that let's stop using hands for start using voice to code!!! With code Assistant
