### ISSUE TITLE
The favicon doesn't appear on Meetup pages

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/hackermonth#3]
The FreeCodeCamp Favicon doesn't seem to appear on the meetup pages, like the [Idea Session page](https://fcc-hyd.github.io/hackermonth/meetup01/). I'm not sure if this is just for me or some problem with the code.

**Comment by vinaypuppal** [comment]
@duttakapil because incorrect reference path to favicon [[see here](https://github.com/fcc-hyd/hackermonth/blob/13a723d26fe3a7742d03d71e95bbb97de6074a1d/meetup01/index.html#L7)]

ca76bf808ed8231f921de56b7721546d7c4dd31c in #4 fixes it
