### ISSUE TITLE
clean up index.css

### ISSUE THREAD

**Issue by vinaypuppal** [fcc-hyd/hackermonth#6]
The index.css is really messed up
- remove multiple definitions for the same stuff
- remove unused css styles
- and combine media queries targeting same screen resolution and move them to bottom of css file

**Comment by AshV** [comment]
Is it something like compiler processing,  or how you are planning to achieve it.

**Comment by AshV** [comment]
Oh,  got it , it's not an idea it's a real issue

**Comment by duttakapil** [comment]
@AshishVishwakarma yup, we messed up the commits, so the code is all messed up right now. Have  to get this done. This should be not that hard to fix through. @vinaypuppal should we give this an "easy-to-fix" label and assign it some beginner?
