### ISSUE TITLE
Build an "ideas" page

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/hackermonth#8]
We should have a page on the site to display all the ideas/projects people are working on. This can be just a list of divs horizontally aligned. We should also display the names and pictures of the people working on those idea/projects. 

Links:
- [GitHub](https://github.com/keshavnarla/Idea-page-for-FCC-Hyd)
- [Trello](https://trello.com/b/YiNev0mW/idea-page-for-hacker-month)
- [Gitter](https://gitter.im/Team-Rookie-HackerMonth/Lobby)

Team :
Waiting for a few to accept invitation

**Comment by keshavnarla** [comment]
Links:-
[GitHub](https://github.com/keshavnarla/Idea-page-for-FCC-Hyd)
[Trello](https://trello.com/b/YiNev0mW/idea-page-for-hacker-month)
[Gitter](https://gitter.im/Team-Rookie-HackerMonth/Lobby)

Team:
Waiting for a few to accept invitation

**Comment by ghost** [comment]
yes im interested

**Comment by ParaRahul** [comment]
I am interested

**Comment by nareshmahendra** [comment]
I am interested

**Comment by keshavnarla** [comment]
Awesome guys..can you ping me on WhatsApp at 900026275 two

**Comment by keshavnarla** [comment]
WhatsApp group link https://chat.whatsapp.com/3IljS7FfNKf2VLvv9lldAr

**Comment by duttakapil** [comment]
@keshavnarla can you update your comment with the github usernames of your team mates?
