### ISSUE TITLE
TTMM App (Expenses Manager) 

### ISSUE THREAD

**Issue by AshV** [fcc-hyd/hackermonth#9]
# TTMM Expenses Manager

Whenever we are on a trip, or other occasion, when many people are spending money on each other, after trip it is very painful to manage expenses, our team is working on a solution for this, we name it as TTMM.

**Get Our Updates Here**
Scheduled tasks at [TTMM Trello](https://trello.com/b/wY7nz9tf/ttmm)
Discussions at [TTMM Gitter](https://gitter.im/TTMM-FCC/Lobby)
Code at [TTMM Repo](https://github.com/TharunBairoju/TTMM)

**Meet Our Team**
@TharunBairoju
@mkkasturi
@AshishVishwakarma

**We are going to use**
HTML & CSS for UI
JS for Business Logic
Firebase for Backend

**Comment by duttakapil** [comment]
@AshishVishwakarma can you update the description with links to the GitHub repo for this project, the Trello board and the Gitter chatroom for your team? Make sure to set the Trello board to public

**Comment by irfan-m-mohammad** [comment]
I have developed an android application similar to this, named "[FolksWallet](https://github.com/nafri-irfan96/FolksWallet)". It is about sharing expenses incurred by people who went for a trip.

**Comment by dsandeepchary** [comment]
I'd like to join this team,..
